# Generated by Django 4.1.4 on 2022-12-08 11:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_alter_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f4ab9084-d351-41bb-b391-972fb45a2a4d'), primary_key=True, serialize=False),
        ),
    ]
